http:
  routers:
    sellplat-frontend-jwodl7-router-12:
      rule: Host(`sentplat.com`)
      service: sellplat-frontend-jwodl7-service-12
      middlewares:
        - redirect-to-https
      entryPoints:
        - web
    sellplat-frontend-jwodl7-router-websecure-12:
      rule: Host(`sentplat.com`)
      service: sellplat-frontend-jwodl7-service-12
      middlewares: []
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    sellplat-frontend-jwodl7-router-15:
      rule: Host(`godlysensation.com`)
      service: sellplat-frontend-jwodl7-service-15
      middlewares:
        - redirect-to-https
      entryPoints:
        - web
    sellplat-frontend-jwodl7-router-websecure-15:
      rule: Host(`godlysensation.com`)
      service: sellplat-frontend-jwodl7-service-15
      middlewares: []
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
    sellplat-frontend-jwodl7-router-20:
      rule: Host(`*.sentplat.com`)
      service: sellplat-frontend-jwodl7-service-20
      middlewares:
        - redirect-to-https
      entryPoints:
        - web
    sellplat-frontend-jwodl7-router-websecure-20:
      rule: Host(`*.sentplat.com`)
      service: sellplat-frontend-jwodl7-service-20
      middlewares: []
      entryPoints:
        - websecure
  services:
    sellplat-frontend-jwodl7-service-12:
      loadBalancer:
        servers:
          - url: http://sellplat-frontend-jwodl7:80
        passHostHeader: true
    sellplat-frontend-jwodl7-service-15:
      loadBalancer:
        servers:
          - url: http://sellplat-frontend-jwodl7:80
        passHostHeader: true
    sellplat-frontend-jwodl7-service-20:
      loadBalancer:
        servers:
          - url: http://sellplat-frontend-jwodl7:80
        passHostHeader: true
