http:
  routers:
    sellplat-backend-cpdnnw-router-13:
      rule: Host(`api.sentplat.com`)
      service: sellplat-backend-cpdnnw-service-13
      middlewares:
        - redirect-to-https
      entryPoints:
        - web
    sellplat-backend-cpdnnw-router-websecure-13:
      rule: Host(`api.sentplat.com`)
      service: sellplat-backend-cpdnnw-service-13
      middlewares: []
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
  services:
    sellplat-backend-cpdnnw-service-13:
      loadBalancer:
        servers:
          - url: http://sellplat-backend-cpdnnw:81
        passHostHeader: true
